// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKGvIHGTeC1_RuzgAQOaaJQzY9Wp2S0b0',
    appId: '1:690153708501:web:1eb6ceb732060a6d7d7b5c',
    messagingSenderId: '690153708501',
    projectId: 'chat-messenger-bdb31',
    authDomain: 'chat-messenger-bdb31.firebaseapp.com',
    storageBucket: 'chat-messenger-bdb31.appspot.com',
    measurementId: 'G-2Q6WG232S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx4sqJhKY1Dba1gKIrrqs3fwZdC-58AZE',
    appId: '1:690153708501:android:7299267ae6f433df7d7b5c',
    messagingSenderId: '690153708501',
    projectId: 'chat-messenger-bdb31',
    storageBucket: 'chat-messenger-bdb31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMQMJdmoxJCWK_WuqBnO_zfAKVg1zz3wI',
    appId: '1:690153708501:ios:bfddcf25a1ddcb537d7b5c',
    messagingSenderId: '690153708501',
    projectId: 'chat-messenger-bdb31',
    storageBucket: 'chat-messenger-bdb31.appspot.com',
    iosClientId: '690153708501-7nrn3ig8b45hmr7tc20qtavm13lo1ike.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMessengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMQMJdmoxJCWK_WuqBnO_zfAKVg1zz3wI',
    appId: '1:690153708501:ios:bfddcf25a1ddcb537d7b5c',
    messagingSenderId: '690153708501',
    projectId: 'chat-messenger-bdb31',
    storageBucket: 'chat-messenger-bdb31.appspot.com',
    iosClientId: '690153708501-7nrn3ig8b45hmr7tc20qtavm13lo1ike.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMessengerApp',
  );
}
